### ISSUE TITLE
Práticas

### ISSUE THREAD

**Issue by thiago-ndev** [tuvtran/project-based-learning#466]
### Is this something you're interested in working on?

- [ ] YES
- [ ] NO

**Comment by simonebogni** [comment]
@thiago-ndev Hi, please don't spam Open Source repositories with fake issues.
It's a really annoying practice. If you want to test how issues work, you can do so on one of your personal repos.
The first rule of Open Source or any development is to "keep the place cleaner than how you found it", not to litter it.
Thank you.
Developers usually look at issue to see how stable is the repository and to see if there is something to improve.
Please close your issue if it's not relevant, because maintainers shouldn't have to deal with this type of stuff.

**Comment by thiago-ndev** [comment]
sorry @simonebogni I didn't know what I was doing.
